### ISSUE TITLE
Failed prop type: invalid prop 'source' supplied to 'Image' when displaying local image

### ISSUE THREAD

**Issue by LEEY19** [ascoders/react-native-image-viewer#53]
Hi @ascoders, I have been using your dependency for some time. Today, I needed to use it for displaying local images. I upgraded to the latest version of your project. A problem appeared. 

When I display the image, there is a warning that goes: Failed prop type: invalid prop 'source' supplied to 'Image'. Then the modal is fully black (no image is shown). However, the weird thing that happens is that when I start scrolling it to the right, and scroll back to left, the image appears. My image array object is something like that :

[{url: "file:///storage/emulated/0/DCIM/Camera/20170531_180343.jpg"}, {url: ...}]

Your help is much appreciated!

**Comment by LEEY19** [comment]
@ascoders after some debugging, I realised that the issue has something to do with how fast the image is invoked to load. Say if I chose to display 4 pictures in the ImageViewer, when I scroll to the right quickly, the image does not get displayed. But if I drag across slowly, it appears.

**Comment by Agentzhao** [comment]
How did you display local images?

> url:"file:./image.jpg" 
is not working

**Comment by zyf970617** [comment]
I have the same problem

**Comment by vincent0225** [comment]
I faced same problem when loading local image but finally solved. Hope my experience can help others.

As mention in issue #48 
there are some logic to handle local file
`
if (image.url.startsWith(`file:`)) {
            imageLoaded = true
        }
`
However, this logic seems only executed when the ImageViewer construct. If I change the source url by set state and re-render, above logic will not execute. Then it will drop to image load fail case.

`invalid prop 'source' supplied to 'Image' ` should be due to I didn't pass 'failImageSource'.
https://github.com/ascoders/react-native-image-viewer/blob/master/src/image-viewer.component.tsx#L452

I tried to check the local file path whether is ready, before render the ImageViewer, the problem finally solved.
`
{this.state.imageUrl != '' ? (
                <ImageViewer
                    imageUrls={[{ url: this.state.imageUrl }]}
                />
              ):null}
`

**Comment by zainozzaini** [comment]
I faced same problem when calling local image. I see in line 92 of built/src/image.viewer.component.js only call .prefetch function before the image will be rendered. Therefore it will trigger error result and flag the `imageStatus.status` as `fail`. So its only valid for remote file calling. 

What I just do is add other filter to defined either its for remote fetch or local. (P/S: the regex is only for http:// or https://.. you may add your own filter other remote prefix  )

`if (react_native_1.Platform.OS !== 'web') {
            const prefetchImagePromise = react_native_1.Image.prefetch(image.url);
            if(image.url.match(/^(http|https):\/\//)){
              prefetchImagePromise.then(() => {
                  imageLoaded = true;
                  if (sizeLoaded) {
                      imageStatus.status = 'success';
                      saveImageSize();
                  }
              }, () => {
                  imageStatus.status = 'fail';
                  saveImageSize();
              });
            }else{
              //for local content
              imageLoaded = true;
              if (sizeLoaded) {
                  imageStatus.status = 'success';
                  saveImageSize();
              }
            }
...
.....
....`

**Comment by ascoders** [comment]
@zainozzaini Thanks!

**Comment by mkamranhamid** [comment]
template strings solved my problem like i had to use
 `source=`${src}` `
