### ISSUE TITLE
Make it simple to build the project on a fresh clone = higher chance of contributions

### ISSUE THREAD

**Issue by jimmystridh** [ascoders/react-native-image-viewer#6]
I want to contribute to the project and as I'm not previously familiar with typescript, installing the correct tools and type definitions was the initial hurdle. Just being able to do an **npm install** and then something like **npm run build** would be awesome.

I figured tsc index.ts --jsx react --experimentalDecorators seems to do the trick when building, provided you have typescript installed?

I guess something like
```
 "devDependencies": {
    "@types/react": "^0.14.37",
    "@types/react-native": "^0.29.35"
  }
```
should be in package.json ?

Then I got stuck on the following:
```
======== Module name 'global' was not resolved. ========
image-viewer/image-viewer.component.tsx(7,29): error TS2307: Cannot find module '../../auto-bind/index'.
image-viewer/image-viewer.component.tsx(8,37): error TS2307: Cannot find module '../../transmit-transparently/index'.
image-viewer/image-viewer.component.tsx(9,23): error TS2307: Cannot find module '../../image-zoom/index'.
image-viewer/image-viewer.component.tsx(81,36): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.

```

are the modules auto-bind, transmit-transparently and image-zoom something you have on your local file system ? Could these use npm packages instead ? And the ObjectConstructor error I have no idea what to do about.

Thanks!

**Comment by ascoders** [comment]
Hello, this project is not a separate management, we have a lot of similar projects are included in a large project. The final output to the web site, you can see the above components's documents, dependences, and demos. http://next.baidu.com/components/common/image-viewer

You can see this component support for Android and IOS, but there is no web version.

In root projects, we will clone all of our own components, and if a component depends on our own components, we will refer to the relative path, such as '../../image-zoom/index' and '../../auto-bind/index'.

When the project is published, all the dependent components will have a corresponding release version, the relative path of the code will be replaced, for example, will replace 'nt-image-zoom' with '../../image-zoom/index'.

There is no way to run alone, now I first think of a way to configure ts to join package.json, the file name and a replacement script, I will think of a way, and now see `Object.assign` error, also because I didn't have to write clearly the configuration of the TS lead, please give me a little time~

**Comment by jimmystridh** [comment]
I see. Thanks for the clarification. Is there a way for me to do a similar clone of the root project to get the same setup ?

**Comment by ascoders** [comment]
Project in the private repository, but because there is no important information, I first open source out.

**Comment by ascoders** [comment]
https://github.com/nt-team/design

**Comment by jimmystridh** [comment]
Thanks! I'll have a look.
